#!/usr/bin/env bash

set -eu
DOTFILES_DIR="${HOME}/.dotfiles"
DOTFILES_HOME_DIR="${DOTFILES_DIR}/home_files"
PERSISTENT_JB_DIR="${HOME}/.gitpod/jetbrains/${JETBRAINS_GITPOD_BACKEND_KIND:-}"
PERSISTENT_DOTFILES_DIR="${DOTFILES_HOME_DIR}/${PERSISTENT_JB_DIR#$HOME/}"
EPHEMERAL_JB_OPTIONS_DIR=(/workspace/.config/JetBrains/RemoteDev-*/options)


(
    set +e
    mkdir -p "${PERSISTENT_DOTFILES_DIR}"
    cp -ar "${EPHEMERAL_JB_OPTIONS_DIR}" "${PERSISTENT_DOTFILES_DIR}" 2>/dev/null

    if test -e "${HOME}/.config/JetBrains"; then
        mkdir -p "${DOTFILES_HOME_DIR}/.config"
        cp -ar "${HOME}/.config/JetBrains" "${DOTFILES_HOME_DIR}/.config"
    fi

    "$HOME/.dotfiles/install.sh"
    cd "${DOTFILES_DIR}"
    git add home_files
    git commit -m 'Automatic commit for updating Jetbrains config'
    git push
)

printf '[info] %s\n' "Successfully cloned ${EPHEMERAL_JB_OPTIONS_DIR} contents to a persistent location"
